### ISSUE TITLE
Cannot read property 'logger' of undefined

### ISSUE THREAD

**Issue by RonAlmog** [rubiin/nestjs-easyconfig#244]
i followed the basic instructions, added /config/.env file,
imported as described in app.module,
imported the service in a feature module, added this to my constructor:
private readonly config: EasyconfigService,
and used it to get the value in a controller:
const adminEmail = this.config.get('ADMIN_EMAIL');
and i'm getting this error:

[Nest] 20948   - 05/23/2020, 4:44:40 PM   [NestFactory] Starting Nest application...
[Nest] 20948   - 05/23/2020, 4:44:40 PM   [ExceptionHandler] Cannot read property 'logger' of undefined +40ms
T**ypeError: Cannot read property 'logger' of undefined
    at new EasyconfigService (C:\Projects\Nuxt\proj\proj-server\node_modules\nestjs-easyconfig\dist\easyconfig.service.js:50:30)**
    at Injector.instantiateClass (C:\Projects\Nuxt\proj\proj-server\node_modules\@nestjs\core\injector\injector.js:289:19)

Any clue?

**Comment by RonAlmog** [comment]
i created a small nest project, just to test this issue. the same problem happened.
here is the repo:
https://github.com/RonAlmog/nest-swagger-test
thanks for any help.

**Comment by rubiin** [comment]
so i reviewed your code and found the problem. you have registered the module in app.module but directly using EasyConfigService without adding it to the dog module. Thats what causing the problem, try to add it on the dog module as well @RonAlmog

**Comment by rubiin** [comment]
Also a quick reminder, if you have imported the module in one of your modules, you may not not re-import it on other modules. The values are written on process.env so you can access these values using process.env.[key]

**Comment by RonAlmog** [comment]
Thanks for your answer!  but that's not true. the service is imported into dog module:
 providers: [EasyconfigService],
Do you know what would solve this confusion? a simple working example.
a nest.js project that is using your component, reading values from .env file, and using them both in app.module (to connect to db, for example) and in feature modules.
Thanks again.

**Comment by rubiin** [comment]
since the lib works on module level, you have to register it individually across all modules you use. i am afraid you cannot directly use the service

**Comment by rubiin** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
